# used to run multiple containers at once
# volumes are used to persist data

version: '3.8'

services:
  user-service:
    build: ./user-service
    ports:
      - 8082:8082
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/TmsUsers
      - PORT=8082
  task-service:
    build: ./task-service
    ports:
      - 8083:8083
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/TmsTasks
      - PORT=8083
      - RABBITMQ_URI=amqp://rabbitmq
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
  rabbitmq:
    image: rabbitmq:3.13.7-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    




volumes:
  mongodb-data:
  rabbitmq-data:
    